version: "3.8"
services:
  calculation-api:
    build:
      context: calculation-api/
      dockerfile: Dockerfile
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Jye1n8LQ20mWJeCO
      MYSQL_DATABASE: calculation_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql-data:
  redis-data: