spring:
  application:
    name: Real-Time Balance Calculation System
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
